apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold-poc
build:
  artifacts:
    - image: skaffold-poc  # Este es el nombre local de la imagen
      docker:
        cacheFrom:
          - skaffold-poc  # Imagen local para el caché
  local:  # Usamos el builder local
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml

